- vignettes/demographic_data.Rmd
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
It updates the demographic vignette as expected in issue #52 with other example on how to use the data
> Dev demographic vigennete moreexamples

- vignettes/demographic_data.Rmd
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
It changes the titles and subtitles of the demographic vignette and change colors of graphs to the ones in the epiverse palette issue #57
> Dev demographic vignette modifications

- README.Rmd
- README.md
- inst/extdata/config.yaml
- vignettes/demographic_data.Rmd
All population projections (pp) were uploaded to the server, documentation was updated with pp information. Also, the config file and the demographic vignette were updated.
It completes the issue #18
> Dev update dem vignette

- README.md
- inst/WORDLIST
- [ X] Tests for the changes have been added (for bug fixes / features)
- [ X] Docs have been added / updated (for bug fixes / features)
- [ X] Checks have been run locally and pass
It was introduced the COVID word to the wordlist and the readme was fixed
> Dev error fixing

- vignettes/climate_data.Rmd
> Dev fix climate vignette

- README.Rmd
- README.md
- vignettes/demographic_data.Rmd
Here are made all changes to fulfill comentaries made in the first user test, presented in issue #77.
Also, one of issue 81, but still not finished here.
> Dev fix dem vignette after user test

- R/documentation.R
- README.Rmd
- README.md
- inst/WORDLIST
- man/dictionary.Rd
- man/list_datasets.Rd
- man/look_up.Rd
- vignettes/climate_data.Rmd
- vignettes/demographic_data.Rmd
- vignettes/documentation_and_dictionaries.Rmd
- vignettes/geospatial_data.Rmd
Address comments in #80 and #81. This included general comments about vignettes and user guides.
> Dev fix documentation

- vignettes/geospatial_data.Rmd
> Update geospatial vignette

- R/divipola.R
- tests/testthat/test-divipola.R
- vignettes/climate_data.Rmd
- vignettes/geospatial_data.Rmd
Include DIVIPOLA auxiliary functions in vignettes
> Dev include divipola vig

- vignettes/documentation_and_dictionaries.Rmd
This PR presents an update to documentation vignette, more specifically regarding the look_up function
> Dev documentation look up function

- R/divipola.R
- tests/testthat/test-divipola.R
Divipola functions' thresholds were modified and a moving window was added for better fitting . (#102).
> Update divipola threshold

- R/divipola.R
- man/name_to_standard_dep.Rd
- man/name_to_standard_mun.Rd
Fix minor spelling and documentation issues
> Fix spelling issues

- .Rbuildignore
- .lintr
- LICENSE
- NEWS.md
- R/dev-utils.R
- README.Rmd
- README.md
- tests/testthat/test-dev-utils.R
- vignettes/documentation_and_dictionaries.Rmd
- vignettes/geospatial_data.Rmd
This PR introduces general changes to the package based on the comments left on the 2nd package review.
> Dev generals pkg review

- R/download_population_projections.R
This PR introduces changes to the population_projections.R file based on the comments of the second package review.
> Modify download_population_projections.R file

- _pkgdown.yml
- vignettes/climate_data.Rmd
- vignettes/demographic_data.Rmd
- vignettes/documentation_and_dictionaries.Rmd
- vignettes/geospatial_data.Rmd
- vignettes/merge_geo_demographic.Rmd
- vignettes/population_projections.Rmd
This PR introduces changes to vignettes and the pkgdown based on the comment of the second package review, presented in the issue #119
> Comments from full package review Vignettes & pkgdown

- .Rbuildignore
- .lintr
- LICENSE
- NEWS.md
- R/dev-utils.R
- README.Rmd
- README.md
- tests/testthat/test-dev-utils.R
- vignettes/documentation_and_dictionaries.Rmd
- vignettes/geospatial_data.Rmd
Reverts epiverse-trace/ColOpenData#125
> Revert "Dev generals pkg review"

- R/download_population_projections.R
Reverts epiverse-trace/ColOpenData#126
> Revert "Modify download_population_projections.R file"

- _pkgdown.yml
- vignettes/climate_data.Rmd
- vignettes/demographic_data.Rmd
- vignettes/documentation_and_dictionaries.Rmd
- vignettes/geospatial_data.Rmd
- vignettes/merge_geo_demographic.Rmd
- vignettes/population_projections.Rmd
Reverts epiverse-trace/ColOpenData#127
> Revert "Comments from full package review Vignettes & pkgdown"

- .github/workflows/lint-changed-files.yml
- .lintr
- LICENSE.md
This PR introduces updates to lint-changed-files.yml and LICENSE.md, as presente in issue #120
> Updates of lint and license

- R/download_climate.R
- tests/testthat/_snaps/aggregate_climate.md
- tests/testthat/test-aggregate_climate.R
- tests/testthat/test-merge_geo_demographic.R
Download climate for municipalities and departments, addressing #142
> Update Climate download

- R/download_climate.R
- R/download_population_projections.R
- README.Rmd
- README.md
- inst/WORDLIST
- tests/testthat/_snaps/download_climate.md
- tests/testthat/_snaps/download_population_projections.md
This PR add words to the wordlist and updates readme.
> updated wordlist and readme
